apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: react-starter-gitops
  namespace: default
spec:
  owner:
    projectName: demo-project-gitops

  # References the ComponentType 
  componentType:
    name: deployment/web-application
    kind: ComponentType

  workflow:
    name: react
    parameters:
      nodeVersion: "20"
      repository:
        url: "https://github.com/openchoreo/sample-workloads"
        revision:
          branch: "main"
        appPath: "/webapp-react-nginx"

  parameters:
    replicas: 2
    port: 80
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"