apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: document-svc
  namespace: default
spec:
  owner:
    projectName: doclet

  componentType:
    name: deployment/service
    kind: ComponentType

  autoBuild: true

  workflow:
    name: docker-gitops-release
    parameters:
      componentName: "document-svc"
      projectName: "doclet"
      repository:
        url: "https://github.com/openchoreo/sample-workloads.git"
        revision:
          branch: "main"
        appPath: "/project-doclet-app/service-go-document"
      docker:
        context: "/project-doclet-app/service-go-document"
        filePath: "/project-doclet-app/service-go-document/Dockerfile"
      workloadDescriptorPath: "workload.yaml"

  parameters:
    exposed: true
    replicas: 1
    port: 8080
